[package]
name = "floem_tiny_skia"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
resvg = "0.33.0"
raw-window-handle = "0.5.1"
futures = "0.3.26"
anyhow = "1.0.69"
peniko = { git = "https://github.com/linebender/peniko", rev = "cafdac9a211a0fb2fec5656bd663d1ac770bcc81" }
swash = "0.1.8"
floem_renderer = { path = "../renderer" }
softbuffer = "0.3.1"
bytemuck = "1.12"
image = { version = "0.24", features = ["jpeg", "png"] }
