[package]
name = "floem_renderer"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
resvg = "0.33.0"
image = { version = "0.24", features = ["jpeg", "png"] }
peniko = { git = "https://github.com/linebender/peniko", rev = "cafdac9a211a0fb2fec5656bd663d1ac770bcc81" }
cosmic-text = { git = "https://github.com/lapce/cosmic-text", rev = "f7a20704d6ebbe8fb82d0bb579c37c53e7ae9747" }
# cosmic-text = { path = "../../cosmic-text" }
